[lection1_button] added style for buttons
js-tasks-ru/htmlcss-20221107_pavel-glukhov pull request #4
Opened 2022-11-22 21:39 UTC by bill-gilbert

2022-11-22 21:40 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-11-23 22:49 UTC, GSemikozov requested changes

2022-11-23 22:49 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    width: 189px;
ширину фиксировать не нужно, она должна зависеть от вложенного контента

2022-11-23 22:49 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    width: 189px;
и не хватает паддингов

2022-11-23 22:49 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    border-radius: 8px;
радиус здесь дублировать не надо, а вот что надо - так это добавить pointer-events: none

2022-11-23 22:49 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    border-radius: 8px;
и disabled будет общим для всех типов - .button:disabled

2022-11-24 21:21 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-11-24 21:59 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-11-27 21:28 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-12-07 16:50 UTC, GSemikozov approved these changes

2022-12-07 16:50 UTC, merged